/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.InsuranceConsultantRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.InsuranceOfficerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Magic.Design.*;
import Magic.Design.MyJLabel;
import Magic.Design.MyTableFormat;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author sreeram
 */
public class ManageInsuranceOfficerRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageInsuranceOfficerRequestJPanel
     */
    private EcoSystem system;
    private UserAccount userAccount;
    private InsuranceOfficerOrganization legalofficerorganization;
    private Enterprise enterprise;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    
    public ManageInsuranceOfficerRequestJPanel(EcoSystem system, UserAccount userAccount, InsuranceOfficerOrganization legalofficerorganization, Enterprise enterprise) {
        initComponents();
        this.system = system;
        this.userAccount = userAccount;
        this.legalofficerorganization = legalofficerorganization;
        this.enterprise = enterprise;
        
        tblLegalOrganisation.getTableHeader().setDefaultRenderer(new MyTableFormat());
        tblLegalOfficer.getTableHeader().setDefaultRenderer(new MyTableFormat());
        populateOrganisationpatientTable();
        populateLegalPatientTable();
        
    }

    public void populateOrganisationpatientTable(){
        DefaultTableModel model = (DefaultTableModel)tblLegalOrganisation.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : legalofficerorganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = request.getSummary();
            row[2] = request.getPatient();
            row[3] = request.getPatient().getName();
            row[4] = request.getPatient().getEmailID();
            row[5] = request.getStatus();
            
            model.addRow(row);
        }
    }
    
  
     public void populateLegalPatientTable(){
        DefaultTableModel model = (DefaultTableModel)tblLegalOfficer.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = request.getPatient();
            row[2] = request.getPatient().getName();
            row[3] = request.getPatient().getEmailID();
            row[4] = request.getUserAccount().getUsername();
            row[5] = request.getStatus();
             
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAssign = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLegalOrganisation = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLegalOfficer = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 221, 228));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAssign.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAssign.setText("Assign to me");
        btnAssign.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 140, 40));

        tblLegalOrganisation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblLegalOrganisation.setForeground(new java.awt.Color(51, 51, 51));
        tblLegalOrganisation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "Summary", "Patient UID", "Patient Name", "Email", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLegalOrganisation.setGridColor(new java.awt.Color(0, 0, 0));
        tblLegalOrganisation.setRowHeight(30);
        jScrollPane2.setViewportView(tblLegalOrganisation);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 990, 190));

        tblLegalOfficer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblLegalOfficer.setForeground(new java.awt.Color(51, 51, 51));
        tblLegalOfficer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "Patient UID", "Patient Name", "Email", "Assigned to", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLegalOfficer.setGridColor(new java.awt.Color(0, 0, 0));
        tblLegalOfficer.setRowHeight(30);
        jScrollPane4.setViewportView(tblLegalOfficer);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 980, 160));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Insurance Approval Request");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 1556, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Send Mail");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 110, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
       int selectedRow = tblLegalOrganisation.getSelectedRow();
        
        if (selectedRow < 0){
           //JOptionPane.showMessageDialog(null, "Please select a row", "Error", JOptionPane.ERROR_MESSAGE);
           JOptionPane.showMessageDialog(null, new JLabel(  "<html><b>Please select a row from the table</b></html>"), "Error", JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            WorkRequest request = (WorkRequest)tblLegalOrganisation.getValueAt(selectedRow, 0);    
           
            if(request.getStatus().equals("Assigned to Insurance Department"))
            {
            request.setStatus("Assign to InsuranceOfficer" + userAccount.getUsername());
            request.setUserAccount(userAccount);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
            else{
            //JOptionPane.showMessageDialog(null, "Work Request is already assigned!" );
            JOptionPane.showMessageDialog(null, new JLabel(  "<html><b>Work Request is already in progress!</b></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
             
            }
            dB4OUtil.storeSystem(system);
            populateOrganisationpatientTable();
            populateLegalPatientTable();
        }
        
    }//GEN-LAST:event_btnAssignActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
int selectedRow = tblLegalOfficer.getSelectedRow();
        if(selectedRow <0){
        //JOptionPane.showMessageDialog(null,"Please select a row");
        JOptionPane.showMessageDialog(null, new JLabel(  "<html><b>Please select a row from the table</b></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
        else{
          // int selectedRow = tblLegalOfficer.getSelectedRow();
            String toEmail = (String) tblLegalOfficer.getValueAt(selectedRow, 3);
System.out.println(toEmail);
            String fromEmail = "anchitha0913@gmail.com";
            String fromEmailPassword = "eekabpucdsvhobrw";
            String subject = "Approval Form for Blood Transfusion";

            Properties props = new Properties();
            props.put("mail.smtp.host", "smtp.gmail.com");
            props.put("mail.smtp.port", "465");
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.socketFactory.port", "465");
            props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");

// Authenticate sender
            Authenticator auth = new Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(fromEmail, fromEmailPassword);
                }
            };

// Create email session
            Session session = Session.getInstance(props, auth);

            try {
                // Create email message
                Message message = new MimeMessage(session);
                message.setFrom(new InternetAddress(fromEmail));
                message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail));
                message.setSubject(subject);
                message.setText(
                        "Hello,\n"
                        + "\n"
                        +"I hope this email finds you well. As part of our insurance process, we require your consent to proceed with the approval of your insurance application.\n" +
"\n" +
"To give your consent, please reply to this email with the following statement:\n" +
"\n" +
"\"I hereby give my consent for the approval of my insurance application.\"\n" +
"\n" +
"We take your privacy and security seriously, and any personal information that you provide to us will be kept strictly confidential.\n" +
"\n" +
"Thank you for your cooperation in this matter. If you have any questions or concerns, please don't hesitate to contact us."
                        + "\n" + "Thanks and Regards,\n"
                        +"Insurance Operations Officer.\n"
                );

                // Send email message
                Transport.send(message);

                System.out.println("Email sent successfully.");
            } catch (MessagingException e) {
                throw new RuntimeException(e);
            }
        if(selectedRow <0){
        //JOptionPane.showMessageDialog(null,"Please select a row");
        JOptionPane.showMessageDialog(null, new JLabel(  "<html><b>Please select a row from the table</b></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
        else{
        WorkRequest request = (WorkRequest)tblLegalOfficer.getValueAt(selectedRow, 0);
       
            request.setStatus("Consent form sent");
            //request.setUserAccount(userAccount);
        //userAccount.getWorkQueue().getWorkRequestList().add(request);
        
        dB4OUtil.storeSystem(system);
        
        populateOrganisationpatientTable();
        populateLegalPatientTable();
        
        JOptionPane.showMessageDialog(null, new JLabel(  "<html><b>Consent Form sent successfully!</b></html>"),"Info", JOptionPane.INFORMATION_MESSAGE);
      
        //JOptionPane.showMessageDialog(null,"Consent Form Sent Successfully", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblLegalOfficer;
    private javax.swing.JTable tblLegalOrganisation;
    // End of variables declaration//GEN-END:variables
}
